// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type ActiveConnection = {
  spacetimeIdentity: __Identity,
  walletAddress: string | undefined,
  connectedAt: __Timestamp,
  lastActivity: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const ActiveConnection = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "spacetimeIdentity", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "walletAddress", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "connectedAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "lastActivity", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ActiveConnection): void {
    __AlgebraicTypeValue.serializeValue(writer, ActiveConnection.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ActiveConnection {
    return __AlgebraicTypeValue.deserializeValue(reader, ActiveConnection.getTypeScriptAlgebraicType());
  },

}

export default ActiveConnection;


