// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SessionStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  get status() {
    return SessionStatus;
  },
  playerCount: __t.u32().name("player_count"),
  paidPlayerCount: __t.u32().name("paid_player_count"),
  trialPlayerCount: __t.u32().name("trial_player_count"),
  prizePool: __t.f64().name("prize_pool"),
  entryFee: __t.f64().name("entry_fee"),
  startTime: __t.timestamp().name("start_time"),
  createdAt: __t.timestamp().name("created_at"),
});
