// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type AddAudioFile = {
  name: string,
  artistName: string,
  songTitle: string,
  ipfsCid: string,
  fileSize: bigint,
  duration: number | undefined,
};
/**
 * An object for generated helper functions.
 */
export const AddAudioFile = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "artistName", algebraicType: __AlgebraicTypeValue.String},
        { name: "songTitle", algebraicType: __AlgebraicTypeValue.String},
        { name: "ipfsCid", algebraicType: __AlgebraicTypeValue.String},
        { name: "fileSize", algebraicType: __AlgebraicTypeValue.U64},
        { name: "duration", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.F64)},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AddAudioFile): void {
    __AlgebraicTypeValue.serializeValue(writer, AddAudioFile.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AddAudioFile {
    return __AlgebraicTypeValue.deserializeValue(reader, AddAudioFile.getTypeScriptAlgebraicType());
  },

}

export default AddAudioFile;

