// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as AdminLevelVariants from './admin_level_variants'

// The tagged union or sum type for the algebraic type `AdminLevel`.
export type AdminLevel = AdminLevelVariants.SuperAdmin |
  AdminLevelVariants.Admin |
  AdminLevelVariants.Moderator;

// A value with helper functions to construct the type.
export const AdminLevel = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  SuperAdmin: { tag: "SuperAdmin" } as const,
  Admin: { tag: "Admin" } as const,
  Moderator: { tag: "Moderator" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "SuperAdmin", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Admin", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Moderator", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AdminLevel): void {
      __AlgebraicTypeValue.serializeValue(writer, AdminLevel.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AdminLevel {
      return __AlgebraicTypeValue.deserializeValue(reader, AdminLevel.getTypeScriptAlgebraicType());
  },

}

export default AdminLevel;


