// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AdminLevel,
} from "./types";


export default __t.row({
  adminIdentity: __t.identity().primaryKey().name("admin_identity"),
  get adminLevel() {
    return AdminLevel.name("admin_level");
  },
  grantedAt: __t.timestamp().name("granted_at"),
  grantedBy: __t.identity().name("granted_by"),
});
