// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { AudioFile } from "./audio_file_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `audio_files`.
 *
 * Obtain a handle from the [`audioFiles`] property on [`RemoteTables`],
 * like `ctx.db.audioFiles`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.audioFiles.on_insert(...)`.
 */
export class AudioFilesTableHandle {
  tableCache: __TableCache<AudioFile>;

  constructor(tableCache: __TableCache<AudioFile>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<AudioFile> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `audio_files`,
   * which allows point queries on the field of the same name
   * via the [`AudioFilesIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.audioFiles.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `audio_files`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): AudioFile | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `name` unique index on the table `audio_files`,
   * which allows point queries on the field of the same name
   * via the [`AudioFilesNameUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.audioFiles.name().find(...)`.
   *
   * Get a handle on the `name` unique index on the table `audio_files`.
   */
  name = {
    // Find the subscribed row whose `name` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): AudioFile | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.name, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: AudioFile) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: AudioFile) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: AudioFile) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: AudioFile) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: AudioFile, newRow: AudioFile) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: AudioFile, newRow: AudioFile) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
