// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  artistName: __t.string().name("artist_name"),
  songTitle: __t.string().name("song_title"),
  ipfsCid: __t.string().name("ipfs_cid"),
  ipfsUrl: __t.string().name("ipfs_url"),
  fileSize: __t.u64().name("file_size"),
  duration: __t.option(__t.f64()),
  uploadedAt: __t.timestamp().name("uploaded_at"),
  uploadedBy: __t.identity().name("uploaded_by"),
});
