// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as EntryStatusVariants from './entry_status_variants'

// The tagged union or sum type for the algebraic type `EntryStatus`.
export type EntryStatus = EntryStatusVariants.Verified |
  EntryStatusVariants.Consumed |
  EntryStatusVariants.Expired;

// A value with helper functions to construct the type.
export const EntryStatus = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Verified: { tag: "Verified" } as const,
  Consumed: { tag: "Consumed" } as const,
  Expired: { tag: "Expired" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Verified", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Consumed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Expired", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: EntryStatus): void {
      __AlgebraicTypeValue.serializeValue(writer, EntryStatus.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): EntryStatus {
      return __AlgebraicTypeValue.deserializeValue(reader, EntryStatus.getTypeScriptAlgebraicType());
  },

}

export default EntryStatus;


