// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { PlayerType } from "./player_type_type";
// Mark import as potentially unused
declare type __keep_PlayerType = PlayerType;


export type GameSession = {
  id: bigint,
  sessionId: string,
  gameId: string,
  walletAddress: string | undefined,
  guestId: string | undefined,
  spacetimeIdentity: __Identity,
  playerType: PlayerType,
  score: number,
  questionsAnswered: number,
  correctAnswers: number,
  startedAt: __Timestamp,
  endedAt: __Timestamp | undefined,
  difficulty: string,
  gameMode: string,
};
/**
 * An object for generated helper functions.
 */
export const GameSession = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "sessionId", algebraicType: __AlgebraicTypeValue.String},
        { name: "gameId", algebraicType: __AlgebraicTypeValue.String},
        { name: "walletAddress", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "guestId", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "spacetimeIdentity", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "playerType", algebraicType: PlayerType.getTypeScriptAlgebraicType()},
        { name: "score", algebraicType: __AlgebraicTypeValue.U32},
        { name: "questionsAnswered", algebraicType: __AlgebraicTypeValue.U32},
        { name: "correctAnswers", algebraicType: __AlgebraicTypeValue.U32},
        { name: "startedAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "endedAt", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.createTimestampType())},
        { name: "difficulty", algebraicType: __AlgebraicTypeValue.String},
        { name: "gameMode", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: GameSession): void {
    __AlgebraicTypeValue.serializeValue(writer, GameSession.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GameSession {
    return __AlgebraicTypeValue.deserializeValue(reader, GameSession.getTypeScriptAlgebraicType());
  },

}

export default GameSession;


