// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EntryStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  walletAddress: __t.option(__t.string()).name("wallet_address"),
  anonId: __t.option(__t.string()).name("anon_id"),
  isTrial: __t.bool().name("is_trial"),
  get status() {
    return EntryStatus;
  },
  paidTxHash: __t.option(__t.string()).name("paid_tx_hash"),
  verifiedAt: __t.timestamp().name("verified_at"),
  createdAt: __t.timestamp().name("created_at"),
});
