// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  guestId: __t.string().name("guest_id"),
  get playerType() {
    return PlayerType.name("player_type");
  },
  score: __t.u32(),
  questionsAnswered: __t.u32().name("questions_answered"),
  correctAnswers: __t.u32().name("correct_answers"),
  startedAt: __t.timestamp().name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  gameData: __t.string().name("game_data"),
});
