// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { GuestPlayer } from "./guest_player_type";
import { PlayerType } from "./player_type_type";
// Mark import as potentially unused
declare type __keep_PlayerType = PlayerType;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `guest_players`.
 *
 * Obtain a handle from the [`guestPlayers`] property on [`RemoteTables`],
 * like `ctx.db.guestPlayers`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.guestPlayers.on_insert(...)`.
 */
export class GuestPlayersTableHandle {
  tableCache: __TableCache<GuestPlayer>;

  constructor(tableCache: __TableCache<GuestPlayer>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<GuestPlayer> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `guestId` unique index on the table `guest_players`,
   * which allows point queries on the field of the same name
   * via the [`GuestPlayersGuestIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.guestPlayers.guestId().find(...)`.
   *
   * Get a handle on the `guestId` unique index on the table `guest_players`.
   */
  guestId = {
    // Find the subscribed row whose `guestId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): GuestPlayer | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.guestId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: GuestPlayer) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: GuestPlayer) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: GuestPlayer) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: GuestPlayer) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: GuestPlayer, newRow: GuestPlayer) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: GuestPlayer, newRow: GuestPlayer) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
