// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerType,
} from "./types";


export default __t.row({
  guestId: __t.string().primaryKey().name("guest_id"),
  name: __t.string(),
  get playerType() {
    return PlayerType.name("player_type");
  },
  gamesPlayed: __t.u32().name("games_played"),
  totalScore: __t.u32().name("total_score"),
  bestScore: __t.u32().name("best_score"),
  achievements: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  lastPlayed: __t.timestamp().name("last_played"),
});
