// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  spacetimeIdentity: __t.identity().primaryKey().name("spacetime_identity"),
  walletAddress: __t.string().name("wallet_address"),
  linkedAt: __t.timestamp().name("linked_at"),
  lastSeen: __t.timestamp().name("last_seen"),
});
