// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { IdentityWalletMapping } from "./identity_wallet_mapping_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `identity_wallet_mapping`.
 *
 * Obtain a handle from the [`identityWalletMapping`] property on [`RemoteTables`],
 * like `ctx.db.identityWalletMapping`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.identityWalletMapping.on_insert(...)`.
 */
export class IdentityWalletMappingTableHandle {
  tableCache: __TableCache<IdentityWalletMapping>;

  constructor(tableCache: __TableCache<IdentityWalletMapping>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<IdentityWalletMapping> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `spacetimeIdentity` unique index on the table `identity_wallet_mapping`,
   * which allows point queries on the field of the same name
   * via the [`IdentityWalletMappingSpacetimeIdentityUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.identityWalletMapping.spacetimeIdentity().find(...)`.
   *
   * Get a handle on the `spacetimeIdentity` unique index on the table `identity_wallet_mapping`.
   */
  spacetimeIdentity = {
    // Find the subscribed row whose `spacetimeIdentity` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: __Identity): IdentityWalletMapping | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.spacetimeIdentity, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `walletAddress` unique index on the table `identity_wallet_mapping`,
   * which allows point queries on the field of the same name
   * via the [`IdentityWalletMappingWalletAddressUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.identityWalletMapping.walletAddress().find(...)`.
   *
   * Get a handle on the `walletAddress` unique index on the table `identity_wallet_mapping`.
   */
  walletAddress = {
    // Find the subscribed row whose `walletAddress` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): IdentityWalletMapping | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.walletAddress, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: IdentityWalletMapping) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: IdentityWalletMapping) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: IdentityWalletMapping) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: IdentityWalletMapping) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: IdentityWalletMapping, newRow: IdentityWalletMapping) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: IdentityWalletMapping, newRow: IdentityWalletMapping) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
