// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type PendingClaim = {
  id: bigint,
  sessionId: string,
  walletAddress: string | undefined,
  gameId: string,
  prizeAmount: number,
  score: number,
  claimed: boolean,
  claimTransactionHash: string | undefined,
  createdAt: __Timestamp,
  expiresAt: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const PendingClaim = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "sessionId", algebraicType: __AlgebraicTypeValue.String},
        { name: "walletAddress", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "gameId", algebraicType: __AlgebraicTypeValue.String},
        { name: "prizeAmount", algebraicType: __AlgebraicTypeValue.F64},
        { name: "score", algebraicType: __AlgebraicTypeValue.U32},
        { name: "claimed", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "claimTransactionHash", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "expiresAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PendingClaim): void {
    __AlgebraicTypeValue.serializeValue(writer, PendingClaim.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PendingClaim {
    return __AlgebraicTypeValue.deserializeValue(reader, PendingClaim.getTypeScriptAlgebraicType());
  },

}

export default PendingClaim;


