// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerType,
} from "./types";


export default __t.row({
  walletAddress: __t.string().primaryKey().name("wallet_address"),
  currentIdentity: __t.option(__t.identity()).name("current_identity"),
  get playerType() {
    return PlayerType.name("player_type");
  },
  totalGames: __t.u32().name("total_games"),
  totalScore: __t.u32().name("total_score"),
  bestScore: __t.u32().name("best_score"),
  averageScore: __t.f64().name("average_score"),
  totalQuestionsAnswered: __t.u32().name("total_questions_answered"),
  totalCorrectAnswers: __t.u32().name("total_correct_answers"),
  lastPlayed: __t.timestamp().name("last_played"),
  createdAt: __t.timestamp().name("created_at"),
});
