// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  walletAddress: __t.string().primaryKey().name("wallet_address"),
  username: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  totalScore: __t.u32().name("total_score"),
  gamesPlayed: __t.u32().name("games_played"),
  bestScore: __t.u32().name("best_score"),
  totalEarnings: __t.f64().name("total_earnings"),
  trialGamesRemaining: __t.u32().name("trial_games_remaining"),
  trialCompleted: __t.bool().name("trial_completed"),
  walletConnected: __t.bool().name("wallet_connected"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
