// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  walletAddress: __t.string().name("wallet_address"),
  sessionId: __t.string().name("session_id"),
  prizeAmount: __t.f64().name("prize_amount"),
  rank: __t.u32(),
  gameTimestamp: __t.timestamp().name("game_timestamp"),
  claimed: __t.bool(),
});
