// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type PrizePool = {
  gameId: string,
  totalAmount: number,
  entryFee: number,
  paidPlayers: number,
  freePlayers: number,
  winnerAddress: string | undefined,
  winnerScore: number | undefined,
  claimed: boolean,
  createdAt: __Timestamp,
  expiresAt: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const PrizePool = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "gameId", algebraicType: __AlgebraicTypeValue.String},
        { name: "totalAmount", algebraicType: __AlgebraicTypeValue.F64},
        { name: "entryFee", algebraicType: __AlgebraicTypeValue.F64},
        { name: "paidPlayers", algebraicType: __AlgebraicTypeValue.U32},
        { name: "freePlayers", algebraicType: __AlgebraicTypeValue.U32},
        { name: "winnerAddress", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "winnerScore", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U32)},
        { name: "claimed", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "expiresAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PrizePool): void {
    __AlgebraicTypeValue.serializeValue(writer, PrizePool.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PrizePool {
    return __AlgebraicTypeValue.deserializeValue(reader, PrizePool.getTypeScriptAlgebraicType());
  },

}

export default PrizePool;


