// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.string().primaryKey().name("game_id"),
  totalAmount: __t.f64().name("total_amount"),
  entryFee: __t.f64().name("entry_fee"),
  paidPlayers: __t.u32().name("paid_players"),
  freePlayers: __t.u32().name("free_players"),
  winnerAddress: __t.option(__t.string()).name("winner_address"),
  winnerScore: __t.option(__t.u32()).name("winner_score"),
  claimed: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
});
