// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.string().name("session_id"),
  walletAddress: __t.option(__t.string()).name("wallet_address"),
  guestId: __t.option(__t.string()).name("guest_id"),
  spacetimeIdentity: __t.identity().name("spacetime_identity"),
  get playerType() {
    return PlayerType.name("player_type");
  },
  audioFileId: __t.string().name("audio_file_id"),
  selectedAnswer: __t.u32().name("selected_answer"),
  correctAnswer: __t.u32().name("correct_answer"),
  isCorrect: __t.bool().name("is_correct"),
  timeTaken: __t.f64().name("time_taken"),
  answeredAt: __t.timestamp().name("answered_at"),
});
