// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  gameId: __t.string(),
  difficulty: __t.string(),
  gameMode: __t.string(),
  playerType: __t.string(),
  walletAddress: __t.option(__t.string()),
  guestId: __t.option(__t.string()),
};
