// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveConnection = __t.object("ActiveConnection", {
  spacetimeIdentity: __t.identity(),
  walletAddress: __t.option(__t.string()),
  connectedAt: __t.timestamp(),
  lastActivity: __t.timestamp(),
});
export type ActiveConnection = __Infer<typeof ActiveConnection>;

export const ActiveGameSession = __t.object("ActiveGameSession", {
  id: __t.u64(),
  sessionId: __t.string(),
  get status() {
    return SessionStatus;
  },
  playerCount: __t.u32(),
  paidPlayerCount: __t.u32(),
  trialPlayerCount: __t.u32(),
  prizePool: __t.f64(),
  entryFee: __t.f64(),
  startTime: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type ActiveGameSession = __Infer<typeof ActiveGameSession>;

export const Admin = __t.object("Admin", {
  adminIdentity: __t.identity(),
  get adminLevel() {
    return AdminLevel;
  },
  grantedAt: __t.timestamp(),
  grantedBy: __t.identity(),
});
export type Admin = __Infer<typeof Admin>;

// The tagged union or sum type for the algebraic type `AdminLevel`.
export const AdminLevel = __t.enum("AdminLevel", {
  SuperAdmin: __t.unit(),
  Admin: __t.unit(),
  Moderator: __t.unit(),
});
export type AdminLevel = __Infer<typeof AdminLevel>;

export const AnonymousSession = __t.object("AnonymousSession", {
  sessionId: __t.string(),
  gamesPlayed: __t.u32(),
  totalScore: __t.u32(),
  bestScore: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AnonymousSession = __Infer<typeof AnonymousSession>;

export const AudioFile = __t.object("AudioFile", {
  id: __t.u64(),
  name: __t.string(),
  artistName: __t.string(),
  songTitle: __t.string(),
  ipfsCid: __t.string(),
  ipfsUrl: __t.string(),
  fileSize: __t.u64(),
  duration: __t.option(__t.f64()),
  uploadedAt: __t.timestamp(),
  uploadedBy: __t.identity(),
});
export type AudioFile = __Infer<typeof AudioFile>;

// The tagged union or sum type for the algebraic type `EntryStatus`.
export const EntryStatus = __t.enum("EntryStatus", {
  Verified: __t.unit(),
  Consumed: __t.unit(),
  Expired: __t.unit(),
});
export type EntryStatus = __Infer<typeof EntryStatus>;

export const GameEntry = __t.object("GameEntry", {
  id: __t.u64(),
  sessionId: __t.string(),
  walletAddress: __t.option(__t.string()),
  anonId: __t.option(__t.string()),
  isTrial: __t.bool(),
  get status() {
    return EntryStatus;
  },
  paidTxHash: __t.option(__t.string()),
  verifiedAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type GameEntry = __Infer<typeof GameEntry>;

export const GameSession = __t.object("GameSession", {
  id: __t.u64(),
  sessionId: __t.string(),
  gameId: __t.string(),
  walletAddress: __t.option(__t.string()),
  guestId: __t.option(__t.string()),
  spacetimeIdentity: __t.identity(),
  get playerType() {
    return PlayerType;
  },
  score: __t.u32(),
  questionsAnswered: __t.u32(),
  correctAnswers: __t.u32(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  difficulty: __t.string(),
  gameMode: __t.string(),
});
export type GameSession = __Infer<typeof GameSession>;

export const GuestGameSession = __t.object("GuestGameSession", {
  id: __t.u64(),
  sessionId: __t.string(),
  guestId: __t.string(),
  get playerType() {
    return PlayerType;
  },
  score: __t.u32(),
  questionsAnswered: __t.u32(),
  correctAnswers: __t.u32(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  gameData: __t.string(),
});
export type GuestGameSession = __Infer<typeof GuestGameSession>;

export const GuestPlayer = __t.object("GuestPlayer", {
  guestId: __t.string(),
  name: __t.string(),
  get playerType() {
    return PlayerType;
  },
  gamesPlayed: __t.u32(),
  totalScore: __t.u32(),
  bestScore: __t.u32(),
  achievements: __t.string(),
  createdAt: __t.timestamp(),
  lastPlayed: __t.timestamp(),
});
export type GuestPlayer = __Infer<typeof GuestPlayer>;

export const IdentityWalletMapping = __t.object("IdentityWalletMapping", {
  spacetimeIdentity: __t.identity(),
  walletAddress: __t.string(),
  linkedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
});
export type IdentityWalletMapping = __Infer<typeof IdentityWalletMapping>;

export const PendingClaim = __t.object("PendingClaim", {
  id: __t.u64(),
  sessionId: __t.string(),
  walletAddress: __t.option(__t.string()),
  gameId: __t.string(),
  prizeAmount: __t.f64(),
  score: __t.u32(),
  claimed: __t.bool(),
  claimTransactionHash: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type PendingClaim = __Infer<typeof PendingClaim>;

export const Player = __t.object("Player", {
  walletAddress: __t.string(),
  username: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
  totalScore: __t.u32(),
  gamesPlayed: __t.u32(),
  bestScore: __t.u32(),
  totalEarnings: __t.f64(),
  trialGamesRemaining: __t.u32(),
  trialCompleted: __t.bool(),
  walletConnected: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerStats = __t.object("PlayerStats", {
  walletAddress: __t.string(),
  currentIdentity: __t.option(__t.identity()),
  get playerType() {
    return PlayerType;
  },
  totalGames: __t.u32(),
  totalScore: __t.u32(),
  bestScore: __t.u32(),
  averageScore: __t.f64(),
  totalQuestionsAnswered: __t.u32(),
  totalCorrectAnswers: __t.u32(),
  lastPlayed: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type PlayerStats = __Infer<typeof PlayerStats>;

// The tagged union or sum type for the algebraic type `PlayerType`.
export const PlayerType = __t.enum("PlayerType", {
  Paid: __t.unit(),
  Trial: __t.unit(),
});
export type PlayerType = __Infer<typeof PlayerType>;

export const PrizeHistory = __t.object("PrizeHistory", {
  id: __t.u64(),
  walletAddress: __t.string(),
  sessionId: __t.string(),
  prizeAmount: __t.f64(),
  rank: __t.u32(),
  gameTimestamp: __t.timestamp(),
  claimed: __t.bool(),
});
export type PrizeHistory = __Infer<typeof PrizeHistory>;

export const PrizePool = __t.object("PrizePool", {
  gameId: __t.string(),
  totalAmount: __t.f64(),
  entryFee: __t.f64(),
  paidPlayers: __t.u32(),
  freePlayers: __t.u32(),
  winnerAddress: __t.option(__t.string()),
  winnerScore: __t.option(__t.u32()),
  claimed: __t.bool(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type PrizePool = __Infer<typeof PrizePool>;

export const QuestionAttempt = __t.object("QuestionAttempt", {
  id: __t.u64(),
  sessionId: __t.string(),
  walletAddress: __t.option(__t.string()),
  guestId: __t.option(__t.string()),
  spacetimeIdentity: __t.identity(),
  get playerType() {
    return PlayerType;
  },
  audioFileId: __t.string(),
  selectedAnswer: __t.u32(),
  correctAnswer: __t.u32(),
  isCorrect: __t.bool(),
  timeTaken: __t.f64(),
  answeredAt: __t.timestamp(),
});
export type QuestionAttempt = __Infer<typeof QuestionAttempt>;

// The tagged union or sum type for the algebraic type `SessionStatus`.
export const SessionStatus = __t.enum("SessionStatus", {
  Waiting: __t.unit(),
  Active: __t.unit(),
  Completed: __t.unit(),
});
export type SessionStatus = __Infer<typeof SessionStatus>;

