// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAudioFileReducer from "../add_audio_file_reducer";
import CreateAnonymousSessionReducer from "../create_anonymous_session_reducer";
import CreateGameEntryReducer from "../create_game_entry_reducer";
import CreateGuestPlayerReducer from "../create_guest_player_reducer";
import CreatePlayerReducer from "../create_player_reducer";
import CreatePrizePoolReducer from "../create_prize_pool_reducer";
import EndGameSessionReducer from "../end_game_session_reducer";
import GetActiveGameSessionReducer from "../get_active_game_session_reducer";
import GetLeaderboardReducer from "../get_leaderboard_reducer";
import GetTopEarnersReducer from "../get_top_earners_reducer";
import GetTrialLeaderboardReducer from "../get_trial_leaderboard_reducer";
import GrantAdminPrivilegesReducer from "../grant_admin_privileges_reducer";
import IdentityConnectedReducer from "../identity_connected_reducer";
import IdentityDisconnectedReducer from "../identity_disconnected_reducer";
import JoinActiveGameSessionReducer from "../join_active_game_session_reducer";
import LinkWalletToIdentityReducer from "../link_wallet_to_identity_reducer";
import MarkEntryConsumedReducer from "../mark_entry_consumed_reducer";
import RecordGuestGameReducer from "../record_guest_game_reducer";
import RecordPrizeDistributionReducer from "../record_prize_distribution_reducer";
import RecordQuestionAttemptReducer from "../record_question_attempt_reducer";
import RevokeAdminPrivilegesReducer from "../revoke_admin_privileges_reducer";
import StartGameSessionReducer from "../start_game_session_reducer";
import UpdateAnonymousSessionReducer from "../update_anonymous_session_reducer";
import UpdateGuestPlayerReducer from "../update_guest_player_reducer";
import UpdatePlayerStatsReducer from "../update_player_stats_reducer";
import UpdatePlayerTypeReducer from "../update_player_type_reducer";
import UpdateTrialStatusReducer from "../update_trial_status_reducer";

export type AddAudioFileParams = __Infer<typeof AddAudioFileReducer>;
export type CreateAnonymousSessionParams = __Infer<typeof CreateAnonymousSessionReducer>;
export type CreateGameEntryParams = __Infer<typeof CreateGameEntryReducer>;
export type CreateGuestPlayerParams = __Infer<typeof CreateGuestPlayerReducer>;
export type CreatePlayerParams = __Infer<typeof CreatePlayerReducer>;
export type CreatePrizePoolParams = __Infer<typeof CreatePrizePoolReducer>;
export type EndGameSessionParams = __Infer<typeof EndGameSessionReducer>;
export type GetActiveGameSessionParams = __Infer<typeof GetActiveGameSessionReducer>;
export type GetLeaderboardParams = __Infer<typeof GetLeaderboardReducer>;
export type GetTopEarnersParams = __Infer<typeof GetTopEarnersReducer>;
export type GetTrialLeaderboardParams = __Infer<typeof GetTrialLeaderboardReducer>;
export type GrantAdminPrivilegesParams = __Infer<typeof GrantAdminPrivilegesReducer>;
export type IdentityConnectedParams = __Infer<typeof IdentityConnectedReducer>;
export type IdentityDisconnectedParams = __Infer<typeof IdentityDisconnectedReducer>;
export type JoinActiveGameSessionParams = __Infer<typeof JoinActiveGameSessionReducer>;
export type LinkWalletToIdentityParams = __Infer<typeof LinkWalletToIdentityReducer>;
export type MarkEntryConsumedParams = __Infer<typeof MarkEntryConsumedReducer>;
export type RecordGuestGameParams = __Infer<typeof RecordGuestGameReducer>;
export type RecordPrizeDistributionParams = __Infer<typeof RecordPrizeDistributionReducer>;
export type RecordQuestionAttemptParams = __Infer<typeof RecordQuestionAttemptReducer>;
export type RevokeAdminPrivilegesParams = __Infer<typeof RevokeAdminPrivilegesReducer>;
export type StartGameSessionParams = __Infer<typeof StartGameSessionReducer>;
export type UpdateAnonymousSessionParams = __Infer<typeof UpdateAnonymousSessionReducer>;
export type UpdateGuestPlayerParams = __Infer<typeof UpdateGuestPlayerReducer>;
export type UpdatePlayerStatsParams = __Infer<typeof UpdatePlayerStatsReducer>;
export type UpdatePlayerTypeParams = __Infer<typeof UpdatePlayerTypeReducer>;
export type UpdateTrialStatusParams = __Infer<typeof UpdateTrialStatusReducer>;

