// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type ActiveGameSession = {
  sessionId: string,
  status: string,
  playerCount: number,
  paidPlayerCount: number,
  trialPlayerCount: number,
  prizePool: number,
  entryFee: number,
  startTime: __Timestamp,
  createdAt: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const ActiveGameSession = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "sessionId", algebraicType: __AlgebraicTypeValue.String},
        { name: "status", algebraicType: __AlgebraicTypeValue.String},
        { name: "playerCount", algebraicType: __AlgebraicTypeValue.U32},
        { name: "paidPlayerCount", algebraicType: __AlgebraicTypeValue.U32},
        { name: "trialPlayerCount", algebraicType: __AlgebraicTypeValue.U32},
        { name: "prizePool", algebraicType: __AlgebraicTypeValue.F64},
        { name: "entryFee", algebraicType: __AlgebraicTypeValue.F64},
        { name: "startTime", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ActiveGameSession): void {
    __AlgebraicTypeValue.serializeValue(writer, ActiveGameSession.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ActiveGameSession {
    return __AlgebraicTypeValue.deserializeValue(reader, ActiveGameSession.getTypeScriptAlgebraicType());
  },

}

export default ActiveGameSession;


