// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type Admin = {
  adminIdentity: __Identity,
  adminLevel: string,
  grantedAt: __Timestamp,
  grantedBy: __Identity,
};
/**
 * An object for generated helper functions.
 */
export const Admin = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "adminIdentity", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "adminLevel", algebraicType: __AlgebraicTypeValue.String},
        { name: "grantedAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "grantedBy", algebraicType: __AlgebraicTypeValue.createIdentityType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: Admin): void {
    __AlgebraicTypeValue.serializeValue(writer, Admin.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Admin {
    return __AlgebraicTypeValue.deserializeValue(reader, Admin.getTypeScriptAlgebraicType());
  },

}

export default Admin;


