// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type GameEntry = {
  sessionId: string,
  walletAddress: string | undefined,
  anonId: string | undefined,
  isTrial: boolean,
  status: string,
  paidTxHash: string | undefined,
  verifiedAt: __Timestamp,
  createdAt: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const GameEntry = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "sessionId", algebraicType: __AlgebraicTypeValue.String},
        { name: "walletAddress", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "anonId", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "isTrial", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "status", algebraicType: __AlgebraicTypeValue.String},
        { name: "paidTxHash", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "verifiedAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: GameEntry): void {
    __AlgebraicTypeValue.serializeValue(writer, GameEntry.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GameEntry {
    return __AlgebraicTypeValue.deserializeValue(reader, GameEntry.getTypeScriptAlgebraicType());
  },

}

export default GameEntry;


