// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.5.0 (commit 0712d3bfbd159367de09efeeeacb54c9d4f0ff61).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { AddAudioFile } from "./add_audio_file_reducer.ts";
export { AddAudioFile };
import { CreateAnonymousSession } from "./create_anonymous_session_reducer.ts";
export { CreateAnonymousSession };
import { CreateGameEntry } from "./create_game_entry_reducer.ts";
export { CreateGameEntry };
import { CreateGuestPlayer } from "./create_guest_player_reducer.ts";
export { CreateGuestPlayer };
import { CreatePendingClaim } from "./create_pending_claim_reducer.ts";
export { CreatePendingClaim };
import { CreatePlayer } from "./create_player_reducer.ts";
export { CreatePlayer };
import { CreatePrizePool } from "./create_prize_pool_reducer.ts";
export { CreatePrizePool };
import { EndGameSession } from "./end_game_session_reducer.ts";
export { EndGameSession };
import { GetActiveGameSession } from "./get_active_game_session_reducer.ts";
export { GetActiveGameSession };
import { GetAllGameEntriesAdmin } from "./get_all_game_entries_admin_reducer.ts";
export { GetAllGameEntriesAdmin };
import { GetAllGameSessionsAdmin } from "./get_all_game_sessions_admin_reducer.ts";
export { GetAllGameSessionsAdmin };
import { GetAllGuestGameSessionsAdmin } from "./get_all_guest_game_sessions_admin_reducer.ts";
export { GetAllGuestGameSessionsAdmin };
import { GetAllGuestPlayersAdmin } from "./get_all_guest_players_admin_reducer.ts";
export { GetAllGuestPlayersAdmin };
import { GetAllPendingClaimsAdmin } from "./get_all_pending_claims_admin_reducer.ts";
export { GetAllPendingClaimsAdmin };
import { GetAllPlayerStatsAdmin } from "./get_all_player_stats_admin_reducer.ts";
export { GetAllPlayerStatsAdmin };
import { GetAllPlayersAdmin } from "./get_all_players_admin_reducer.ts";
export { GetAllPlayersAdmin };
import { GetAllQuestionAttemptsAdmin } from "./get_all_question_attempts_admin_reducer.ts";
export { GetAllQuestionAttemptsAdmin };
import { GetLeaderboard } from "./get_leaderboard_reducer.ts";
export { GetLeaderboard };
import { GetLeaderboardAdmin } from "./get_leaderboard_admin_reducer.ts";
export { GetLeaderboardAdmin };
import { GetPlayerStats } from "./get_player_stats_reducer.ts";
export { GetPlayerStats };
import { GetRandomAudioFiles } from "./get_random_audio_files_reducer.ts";
export { GetRandomAudioFiles };
import { GetTopEarners } from "./get_top_earners_reducer.ts";
export { GetTopEarners };
import { GetTrialLeaderboard } from "./get_trial_leaderboard_reducer.ts";
export { GetTrialLeaderboard };
import { GetTrialLeaderboardAdmin } from "./get_trial_leaderboard_admin_reducer.ts";
export { GetTrialLeaderboardAdmin };
import { GrantAdminPrivileges } from "./grant_admin_privileges_reducer.ts";
export { GrantAdminPrivileges };
import { IdentityConnected } from "./identity_connected_reducer.ts";
export { IdentityConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { JoinActiveGameSession } from "./join_active_game_session_reducer.ts";
export { JoinActiveGameSession };
import { ListAdmins } from "./list_admins_reducer.ts";
export { ListAdmins };
import { MarkClaimClaimed } from "./mark_claim_claimed_reducer.ts";
export { MarkClaimClaimed };
import { MarkEntryConsumed } from "./mark_entry_consumed_reducer.ts";
export { MarkEntryConsumed };
import { RecordGuestGame } from "./record_guest_game_reducer.ts";
export { RecordGuestGame };
import { RecordPrizeDistribution } from "./record_prize_distribution_reducer.ts";
export { RecordPrizeDistribution };
import { RecordQuestionAttempt } from "./record_question_attempt_reducer.ts";
export { RecordQuestionAttempt };
import { RevokeAdminPrivileges } from "./revoke_admin_privileges_reducer.ts";
export { RevokeAdminPrivileges };
import { StartGameSession } from "./start_game_session_reducer.ts";
export { StartGameSession };
import { UpdateAnonymousSession } from "./update_anonymous_session_reducer.ts";
export { UpdateAnonymousSession };
import { UpdateGuestPlayer } from "./update_guest_player_reducer.ts";
export { UpdateGuestPlayer };
import { UpdatePlayerStats } from "./update_player_stats_reducer.ts";
export { UpdatePlayerStats };
import { UpdatePlayerType } from "./update_player_type_reducer.ts";
export { UpdatePlayerType };
import { UpdatePrizePool } from "./update_prize_pool_reducer.ts";
export { UpdatePrizePool };
import { UpdateTrialStatus } from "./update_trial_status_reducer.ts";
export { UpdateTrialStatus };

// Import and reexport all table handle types
import { ActiveGameSessionsTableHandle } from "./active_game_sessions_table.ts";
export { ActiveGameSessionsTableHandle };
import { AdminsTableHandle } from "./admins_table.ts";
export { AdminsTableHandle };
import { AnonymousSessionsTableHandle } from "./anonymous_sessions_table.ts";
export { AnonymousSessionsTableHandle };
import { AudioFilesTableHandle } from "./audio_files_table.ts";
export { AudioFilesTableHandle };
import { GameEntriesTableHandle } from "./game_entries_table.ts";
export { GameEntriesTableHandle };
import { GameSessionsTableHandle } from "./game_sessions_table.ts";
export { GameSessionsTableHandle };
import { GuestGameSessionsTableHandle } from "./guest_game_sessions_table.ts";
export { GuestGameSessionsTableHandle };
import { GuestPlayersTableHandle } from "./guest_players_table.ts";
export { GuestPlayersTableHandle };
import { PendingClaimsTableHandle } from "./pending_claims_table.ts";
export { PendingClaimsTableHandle };
import { PlayerStatsTableHandle } from "./player_stats_table.ts";
export { PlayerStatsTableHandle };
import { PlayersTableHandle } from "./players_table.ts";
export { PlayersTableHandle };
import { PrizeHistoryTableHandle } from "./prize_history_table.ts";
export { PrizeHistoryTableHandle };
import { PrizePoolsTableHandle } from "./prize_pools_table.ts";
export { PrizePoolsTableHandle };
import { QuestionAttemptsTableHandle } from "./question_attempts_table.ts";
export { QuestionAttemptsTableHandle };

// Import and reexport all types
import { ActiveGameSession } from "./active_game_session_type.ts";
export { ActiveGameSession };
import { Admin } from "./admin_type.ts";
export { Admin };
import { AnonymousSession } from "./anonymous_session_type.ts";
export { AnonymousSession };
import { AudioFile } from "./audio_file_type.ts";
export { AudioFile };
import { GameEntry } from "./game_entry_type.ts";
export { GameEntry };
import { GameSession } from "./game_session_type.ts";
export { GameSession };
import { GuestGameSession } from "./guest_game_session_type.ts";
export { GuestGameSession };
import { GuestPlayer } from "./guest_player_type.ts";
export { GuestPlayer };
import { PendingClaim } from "./pending_claim_type.ts";
export { PendingClaim };
import { Player } from "./player_type.ts";
export { Player };
import { PlayerStats } from "./player_stats_type.ts";
export { PlayerStats };
import { PrizeHistory } from "./prize_history_type.ts";
export { PrizeHistory };
import { PrizePool } from "./prize_pool_type.ts";
export { PrizePool };
import { QuestionAttempt } from "./question_attempt_type.ts";
export { QuestionAttempt };

const REMOTE_MODULE = {
  tables: {
    active_game_sessions: {
      tableName: "active_game_sessions",
      rowType: ActiveGameSession.getTypeScriptAlgebraicType(),
    },
    admins: {
      tableName: "admins",
      rowType: Admin.getTypeScriptAlgebraicType(),
    },
    anonymous_sessions: {
      tableName: "anonymous_sessions",
      rowType: AnonymousSession.getTypeScriptAlgebraicType(),
    },
    audio_files: {
      tableName: "audio_files",
      rowType: AudioFile.getTypeScriptAlgebraicType(),
    },
    game_entries: {
      tableName: "game_entries",
      rowType: GameEntry.getTypeScriptAlgebraicType(),
    },
    game_sessions: {
      tableName: "game_sessions",
      rowType: GameSession.getTypeScriptAlgebraicType(),
    },
    guest_game_sessions: {
      tableName: "guest_game_sessions",
      rowType: GuestGameSession.getTypeScriptAlgebraicType(),
    },
    guest_players: {
      tableName: "guest_players",
      rowType: GuestPlayer.getTypeScriptAlgebraicType(),
    },
    pending_claims: {
      tableName: "pending_claims",
      rowType: PendingClaim.getTypeScriptAlgebraicType(),
    },
    player_stats: {
      tableName: "player_stats",
      rowType: PlayerStats.getTypeScriptAlgebraicType(),
    },
    players: {
      tableName: "players",
      rowType: Player.getTypeScriptAlgebraicType(),
    },
    prize_history: {
      tableName: "prize_history",
      rowType: PrizeHistory.getTypeScriptAlgebraicType(),
    },
    prize_pools: {
      tableName: "prize_pools",
      rowType: PrizePool.getTypeScriptAlgebraicType(),
    },
    question_attempts: {
      tableName: "question_attempts",
      rowType: QuestionAttempt.getTypeScriptAlgebraicType(),
    },
  },
  reducers: {
    add_audio_file: {
      reducerName: "add_audio_file",
      argsType: AddAudioFile.getTypeScriptAlgebraicType(),
    },
    create_anonymous_session: {
      reducerName: "create_anonymous_session",
      argsType: CreateAnonymousSession.getTypeScriptAlgebraicType(),
    },
    create_game_entry: {
      reducerName: "create_game_entry",
      argsType: CreateGameEntry.getTypeScriptAlgebraicType(),
    },
    create_guest_player: {
      reducerName: "create_guest_player",
      argsType: CreateGuestPlayer.getTypeScriptAlgebraicType(),
    },
    create_pending_claim: {
      reducerName: "create_pending_claim",
      argsType: CreatePendingClaim.getTypeScriptAlgebraicType(),
    },
    create_player: {
      reducerName: "create_player",
      argsType: CreatePlayer.getTypeScriptAlgebraicType(),
    },
    create_prize_pool: {
      reducerName: "create_prize_pool",
      argsType: CreatePrizePool.getTypeScriptAlgebraicType(),
    },
    end_game_session: {
      reducerName: "end_game_session",
      argsType: EndGameSession.getTypeScriptAlgebraicType(),
    },
    get_active_game_session: {
      reducerName: "get_active_game_session",
      argsType: GetActiveGameSession.getTypeScriptAlgebraicType(),
    },
    get_all_game_entries_admin: {
      reducerName: "get_all_game_entries_admin",
      argsType: GetAllGameEntriesAdmin.getTypeScriptAlgebraicType(),
    },
    get_all_game_sessions_admin: {
      reducerName: "get_all_game_sessions_admin",
      argsType: GetAllGameSessionsAdmin.getTypeScriptAlgebraicType(),
    },
    get_all_guest_game_sessions_admin: {
      reducerName: "get_all_guest_game_sessions_admin",
      argsType: GetAllGuestGameSessionsAdmin.getTypeScriptAlgebraicType(),
    },
    get_all_guest_players_admin: {
      reducerName: "get_all_guest_players_admin",
      argsType: GetAllGuestPlayersAdmin.getTypeScriptAlgebraicType(),
    },
    get_all_pending_claims_admin: {
      reducerName: "get_all_pending_claims_admin",
      argsType: GetAllPendingClaimsAdmin.getTypeScriptAlgebraicType(),
    },
    get_all_player_stats_admin: {
      reducerName: "get_all_player_stats_admin",
      argsType: GetAllPlayerStatsAdmin.getTypeScriptAlgebraicType(),
    },
    get_all_players_admin: {
      reducerName: "get_all_players_admin",
      argsType: GetAllPlayersAdmin.getTypeScriptAlgebraicType(),
    },
    get_all_question_attempts_admin: {
      reducerName: "get_all_question_attempts_admin",
      argsType: GetAllQuestionAttemptsAdmin.getTypeScriptAlgebraicType(),
    },
    get_leaderboard: {
      reducerName: "get_leaderboard",
      argsType: GetLeaderboard.getTypeScriptAlgebraicType(),
    },
    get_leaderboard_admin: {
      reducerName: "get_leaderboard_admin",
      argsType: GetLeaderboardAdmin.getTypeScriptAlgebraicType(),
    },
    get_player_stats: {
      reducerName: "get_player_stats",
      argsType: GetPlayerStats.getTypeScriptAlgebraicType(),
    },
    get_random_audio_files: {
      reducerName: "get_random_audio_files",
      argsType: GetRandomAudioFiles.getTypeScriptAlgebraicType(),
    },
    get_top_earners: {
      reducerName: "get_top_earners",
      argsType: GetTopEarners.getTypeScriptAlgebraicType(),
    },
    get_trial_leaderboard: {
      reducerName: "get_trial_leaderboard",
      argsType: GetTrialLeaderboard.getTypeScriptAlgebraicType(),
    },
    get_trial_leaderboard_admin: {
      reducerName: "get_trial_leaderboard_admin",
      argsType: GetTrialLeaderboardAdmin.getTypeScriptAlgebraicType(),
    },
    grant_admin_privileges: {
      reducerName: "grant_admin_privileges",
      argsType: GrantAdminPrivileges.getTypeScriptAlgebraicType(),
    },
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    join_active_game_session: {
      reducerName: "join_active_game_session",
      argsType: JoinActiveGameSession.getTypeScriptAlgebraicType(),
    },
    list_admins: {
      reducerName: "list_admins",
      argsType: ListAdmins.getTypeScriptAlgebraicType(),
    },
    mark_claim_claimed: {
      reducerName: "mark_claim_claimed",
      argsType: MarkClaimClaimed.getTypeScriptAlgebraicType(),
    },
    mark_entry_consumed: {
      reducerName: "mark_entry_consumed",
      argsType: MarkEntryConsumed.getTypeScriptAlgebraicType(),
    },
    record_guest_game: {
      reducerName: "record_guest_game",
      argsType: RecordGuestGame.getTypeScriptAlgebraicType(),
    },
    record_prize_distribution: {
      reducerName: "record_prize_distribution",
      argsType: RecordPrizeDistribution.getTypeScriptAlgebraicType(),
    },
    record_question_attempt: {
      reducerName: "record_question_attempt",
      argsType: RecordQuestionAttempt.getTypeScriptAlgebraicType(),
    },
    revoke_admin_privileges: {
      reducerName: "revoke_admin_privileges",
      argsType: RevokeAdminPrivileges.getTypeScriptAlgebraicType(),
    },
    start_game_session: {
      reducerName: "start_game_session",
      argsType: StartGameSession.getTypeScriptAlgebraicType(),
    },
    update_anonymous_session: {
      reducerName: "update_anonymous_session",
      argsType: UpdateAnonymousSession.getTypeScriptAlgebraicType(),
    },
    update_guest_player: {
      reducerName: "update_guest_player",
      argsType: UpdateGuestPlayer.getTypeScriptAlgebraicType(),
    },
    update_player_stats: {
      reducerName: "update_player_stats",
      argsType: UpdatePlayerStats.getTypeScriptAlgebraicType(),
    },
    update_player_type: {
      reducerName: "update_player_type",
      argsType: UpdatePlayerType.getTypeScriptAlgebraicType(),
    },
    update_prize_pool: {
      reducerName: "update_prize_pool",
      argsType: UpdatePrizePool.getTypeScriptAlgebraicType(),
    },
    update_trial_status: {
      reducerName: "update_trial_status",
      argsType: UpdateTrialStatus.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.5.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddAudioFile", args: AddAudioFile }
| { name: "CreateAnonymousSession", args: CreateAnonymousSession }
| { name: "CreateGameEntry", args: CreateGameEntry }
| { name: "CreateGuestPlayer", args: CreateGuestPlayer }
| { name: "CreatePendingClaim", args: CreatePendingClaim }
| { name: "CreatePlayer", args: CreatePlayer }
| { name: "CreatePrizePool", args: CreatePrizePool }
| { name: "EndGameSession", args: EndGameSession }
| { name: "GetActiveGameSession", args: GetActiveGameSession }
| { name: "GetAllGameEntriesAdmin", args: GetAllGameEntriesAdmin }
| { name: "GetAllGameSessionsAdmin", args: GetAllGameSessionsAdmin }
| { name: "GetAllGuestGameSessionsAdmin", args: GetAllGuestGameSessionsAdmin }
| { name: "GetAllGuestPlayersAdmin", args: GetAllGuestPlayersAdmin }
| { name: "GetAllPendingClaimsAdmin", args: GetAllPendingClaimsAdmin }
| { name: "GetAllPlayerStatsAdmin", args: GetAllPlayerStatsAdmin }
| { name: "GetAllPlayersAdmin", args: GetAllPlayersAdmin }
| { name: "GetAllQuestionAttemptsAdmin", args: GetAllQuestionAttemptsAdmin }
| { name: "GetLeaderboard", args: GetLeaderboard }
| { name: "GetLeaderboardAdmin", args: GetLeaderboardAdmin }
| { name: "GetPlayerStats", args: GetPlayerStats }
| { name: "GetRandomAudioFiles", args: GetRandomAudioFiles }
| { name: "GetTopEarners", args: GetTopEarners }
| { name: "GetTrialLeaderboard", args: GetTrialLeaderboard }
| { name: "GetTrialLeaderboardAdmin", args: GetTrialLeaderboardAdmin }
| { name: "GrantAdminPrivileges", args: GrantAdminPrivileges }
| { name: "IdentityConnected", args: IdentityConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "JoinActiveGameSession", args: JoinActiveGameSession }
| { name: "ListAdmins", args: ListAdmins }
| { name: "MarkClaimClaimed", args: MarkClaimClaimed }
| { name: "MarkEntryConsumed", args: MarkEntryConsumed }
| { name: "RecordGuestGame", args: RecordGuestGame }
| { name: "RecordPrizeDistribution", args: RecordPrizeDistribution }
| { name: "RecordQuestionAttempt", args: RecordQuestionAttempt }
| { name: "RevokeAdminPrivileges", args: RevokeAdminPrivileges }
| { name: "StartGameSession", args: StartGameSession }
| { name: "UpdateAnonymousSession", args: UpdateAnonymousSession }
| { name: "UpdateGuestPlayer", args: UpdateGuestPlayer }
| { name: "UpdatePlayerStats", args: UpdatePlayerStats }
| { name: "UpdatePlayerType", args: UpdatePlayerType }
| { name: "UpdatePrizePool", args: UpdatePrizePool }
| { name: "UpdateTrialStatus", args: UpdateTrialStatus }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addAudioFile(name: string, artistName: string, songTitle: string, ipfsCid: string, fileSize: bigint, duration: number | undefined) {
    const __args = { name, artistName, songTitle, ipfsCid, fileSize, duration };
    let __writer = new __BinaryWriter(1024);
    AddAudioFile.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_audio_file", __argsBuffer, this.setCallReducerFlags.addAudioFileFlags);
  }

  onAddAudioFile(callback: (ctx: ReducerEventContext, name: string, artistName: string, songTitle: string, ipfsCid: string, fileSize: bigint, duration: number | undefined) => void) {
    this.connection.onReducer("add_audio_file", callback);
  }

  removeOnAddAudioFile(callback: (ctx: ReducerEventContext, name: string, artistName: string, songTitle: string, ipfsCid: string, fileSize: bigint, duration: number | undefined) => void) {
    this.connection.offReducer("add_audio_file", callback);
  }

  createAnonymousSession(sessionId: string) {
    const __args = { sessionId };
    let __writer = new __BinaryWriter(1024);
    CreateAnonymousSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_anonymous_session", __argsBuffer, this.setCallReducerFlags.createAnonymousSessionFlags);
  }

  onCreateAnonymousSession(callback: (ctx: ReducerEventContext, sessionId: string) => void) {
    this.connection.onReducer("create_anonymous_session", callback);
  }

  removeOnCreateAnonymousSession(callback: (ctx: ReducerEventContext, sessionId: string) => void) {
    this.connection.offReducer("create_anonymous_session", callback);
  }

  createGameEntry(sessionId: string, walletAddress: string | undefined, anonId: string | undefined, isTrial: boolean, paidTxHash: string | undefined) {
    const __args = { sessionId, walletAddress, anonId, isTrial, paidTxHash };
    let __writer = new __BinaryWriter(1024);
    CreateGameEntry.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_game_entry", __argsBuffer, this.setCallReducerFlags.createGameEntryFlags);
  }

  onCreateGameEntry(callback: (ctx: ReducerEventContext, sessionId: string, walletAddress: string | undefined, anonId: string | undefined, isTrial: boolean, paidTxHash: string | undefined) => void) {
    this.connection.onReducer("create_game_entry", callback);
  }

  removeOnCreateGameEntry(callback: (ctx: ReducerEventContext, sessionId: string, walletAddress: string | undefined, anonId: string | undefined, isTrial: boolean, paidTxHash: string | undefined) => void) {
    this.connection.offReducer("create_game_entry", callback);
  }

  createGuestPlayer(guestId: string, name: string) {
    const __args = { guestId, name };
    let __writer = new __BinaryWriter(1024);
    CreateGuestPlayer.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_guest_player", __argsBuffer, this.setCallReducerFlags.createGuestPlayerFlags);
  }

  onCreateGuestPlayer(callback: (ctx: ReducerEventContext, guestId: string, name: string) => void) {
    this.connection.onReducer("create_guest_player", callback);
  }

  removeOnCreateGuestPlayer(callback: (ctx: ReducerEventContext, guestId: string, name: string) => void) {
    this.connection.offReducer("create_guest_player", callback);
  }

  createPendingClaim(sessionId: string, walletAddress: string | undefined, gameId: string, prizeAmount: number, score: number) {
    const __args = { sessionId, walletAddress, gameId, prizeAmount, score };
    let __writer = new __BinaryWriter(1024);
    CreatePendingClaim.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_pending_claim", __argsBuffer, this.setCallReducerFlags.createPendingClaimFlags);
  }

  onCreatePendingClaim(callback: (ctx: ReducerEventContext, sessionId: string, walletAddress: string | undefined, gameId: string, prizeAmount: number, score: number) => void) {
    this.connection.onReducer("create_pending_claim", callback);
  }

  removeOnCreatePendingClaim(callback: (ctx: ReducerEventContext, sessionId: string, walletAddress: string | undefined, gameId: string, prizeAmount: number, score: number) => void) {
    this.connection.offReducer("create_pending_claim", callback);
  }

  createPlayer(walletAddress: string, username: string | undefined) {
    const __args = { walletAddress, username };
    let __writer = new __BinaryWriter(1024);
    CreatePlayer.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_player", __argsBuffer, this.setCallReducerFlags.createPlayerFlags);
  }

  onCreatePlayer(callback: (ctx: ReducerEventContext, walletAddress: string, username: string | undefined) => void) {
    this.connection.onReducer("create_player", callback);
  }

  removeOnCreatePlayer(callback: (ctx: ReducerEventContext, walletAddress: string, username: string | undefined) => void) {
    this.connection.offReducer("create_player", callback);
  }

  createPrizePool(gameId: string, entryFee: number) {
    const __args = { gameId, entryFee };
    let __writer = new __BinaryWriter(1024);
    CreatePrizePool.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_prize_pool", __argsBuffer, this.setCallReducerFlags.createPrizePoolFlags);
  }

  onCreatePrizePool(callback: (ctx: ReducerEventContext, gameId: string, entryFee: number) => void) {
    this.connection.onReducer("create_prize_pool", callback);
  }

  removeOnCreatePrizePool(callback: (ctx: ReducerEventContext, gameId: string, entryFee: number) => void) {
    this.connection.offReducer("create_prize_pool", callback);
  }

  endGameSession(sessionId: string) {
    const __args = { sessionId };
    let __writer = new __BinaryWriter(1024);
    EndGameSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("end_game_session", __argsBuffer, this.setCallReducerFlags.endGameSessionFlags);
  }

  onEndGameSession(callback: (ctx: ReducerEventContext, sessionId: string) => void) {
    this.connection.onReducer("end_game_session", callback);
  }

  removeOnEndGameSession(callback: (ctx: ReducerEventContext, sessionId: string) => void) {
    this.connection.offReducer("end_game_session", callback);
  }

  getActiveGameSession() {
    this.connection.callReducer("get_active_game_session", new Uint8Array(0), this.setCallReducerFlags.getActiveGameSessionFlags);
  }

  onGetActiveGameSession(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_active_game_session", callback);
  }

  removeOnGetActiveGameSession(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_active_game_session", callback);
  }

  getAllGameEntriesAdmin() {
    this.connection.callReducer("get_all_game_entries_admin", new Uint8Array(0), this.setCallReducerFlags.getAllGameEntriesAdminFlags);
  }

  onGetAllGameEntriesAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_game_entries_admin", callback);
  }

  removeOnGetAllGameEntriesAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_game_entries_admin", callback);
  }

  getAllGameSessionsAdmin() {
    this.connection.callReducer("get_all_game_sessions_admin", new Uint8Array(0), this.setCallReducerFlags.getAllGameSessionsAdminFlags);
  }

  onGetAllGameSessionsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_game_sessions_admin", callback);
  }

  removeOnGetAllGameSessionsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_game_sessions_admin", callback);
  }

  getAllGuestGameSessionsAdmin() {
    this.connection.callReducer("get_all_guest_game_sessions_admin", new Uint8Array(0), this.setCallReducerFlags.getAllGuestGameSessionsAdminFlags);
  }

  onGetAllGuestGameSessionsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_guest_game_sessions_admin", callback);
  }

  removeOnGetAllGuestGameSessionsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_guest_game_sessions_admin", callback);
  }

  getAllGuestPlayersAdmin() {
    this.connection.callReducer("get_all_guest_players_admin", new Uint8Array(0), this.setCallReducerFlags.getAllGuestPlayersAdminFlags);
  }

  onGetAllGuestPlayersAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_guest_players_admin", callback);
  }

  removeOnGetAllGuestPlayersAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_guest_players_admin", callback);
  }

  getAllPendingClaimsAdmin() {
    this.connection.callReducer("get_all_pending_claims_admin", new Uint8Array(0), this.setCallReducerFlags.getAllPendingClaimsAdminFlags);
  }

  onGetAllPendingClaimsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_pending_claims_admin", callback);
  }

  removeOnGetAllPendingClaimsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_pending_claims_admin", callback);
  }

  getAllPlayerStatsAdmin() {
    this.connection.callReducer("get_all_player_stats_admin", new Uint8Array(0), this.setCallReducerFlags.getAllPlayerStatsAdminFlags);
  }

  onGetAllPlayerStatsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_player_stats_admin", callback);
  }

  removeOnGetAllPlayerStatsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_player_stats_admin", callback);
  }

  getAllPlayersAdmin() {
    this.connection.callReducer("get_all_players_admin", new Uint8Array(0), this.setCallReducerFlags.getAllPlayersAdminFlags);
  }

  onGetAllPlayersAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_players_admin", callback);
  }

  removeOnGetAllPlayersAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_players_admin", callback);
  }

  getAllQuestionAttemptsAdmin() {
    this.connection.callReducer("get_all_question_attempts_admin", new Uint8Array(0), this.setCallReducerFlags.getAllQuestionAttemptsAdminFlags);
  }

  onGetAllQuestionAttemptsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_question_attempts_admin", callback);
  }

  removeOnGetAllQuestionAttemptsAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_question_attempts_admin", callback);
  }

  getLeaderboard(limit: number) {
    const __args = { limit };
    let __writer = new __BinaryWriter(1024);
    GetLeaderboard.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("get_leaderboard", __argsBuffer, this.setCallReducerFlags.getLeaderboardFlags);
  }

  onGetLeaderboard(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.onReducer("get_leaderboard", callback);
  }

  removeOnGetLeaderboard(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.offReducer("get_leaderboard", callback);
  }

  getLeaderboardAdmin() {
    this.connection.callReducer("get_leaderboard_admin", new Uint8Array(0), this.setCallReducerFlags.getLeaderboardAdminFlags);
  }

  onGetLeaderboardAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_leaderboard_admin", callback);
  }

  removeOnGetLeaderboardAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_leaderboard_admin", callback);
  }

  getPlayerStats() {
    this.connection.callReducer("get_player_stats", new Uint8Array(0), this.setCallReducerFlags.getPlayerStatsFlags);
  }

  onGetPlayerStats(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_player_stats", callback);
  }

  removeOnGetPlayerStats(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_player_stats", callback);
  }

  getRandomAudioFiles(count: number) {
    const __args = { count };
    let __writer = new __BinaryWriter(1024);
    GetRandomAudioFiles.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("get_random_audio_files", __argsBuffer, this.setCallReducerFlags.getRandomAudioFilesFlags);
  }

  onGetRandomAudioFiles(callback: (ctx: ReducerEventContext, count: number) => void) {
    this.connection.onReducer("get_random_audio_files", callback);
  }

  removeOnGetRandomAudioFiles(callback: (ctx: ReducerEventContext, count: number) => void) {
    this.connection.offReducer("get_random_audio_files", callback);
  }

  getTopEarners(limit: number) {
    const __args = { limit };
    let __writer = new __BinaryWriter(1024);
    GetTopEarners.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("get_top_earners", __argsBuffer, this.setCallReducerFlags.getTopEarnersFlags);
  }

  onGetTopEarners(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.onReducer("get_top_earners", callback);
  }

  removeOnGetTopEarners(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.offReducer("get_top_earners", callback);
  }

  getTrialLeaderboard(limit: number) {
    const __args = { limit };
    let __writer = new __BinaryWriter(1024);
    GetTrialLeaderboard.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("get_trial_leaderboard", __argsBuffer, this.setCallReducerFlags.getTrialLeaderboardFlags);
  }

  onGetTrialLeaderboard(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.onReducer("get_trial_leaderboard", callback);
  }

  removeOnGetTrialLeaderboard(callback: (ctx: ReducerEventContext, limit: number) => void) {
    this.connection.offReducer("get_trial_leaderboard", callback);
  }

  getTrialLeaderboardAdmin() {
    this.connection.callReducer("get_trial_leaderboard_admin", new Uint8Array(0), this.setCallReducerFlags.getTrialLeaderboardAdminFlags);
  }

  onGetTrialLeaderboardAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_trial_leaderboard_admin", callback);
  }

  removeOnGetTrialLeaderboardAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_trial_leaderboard_admin", callback);
  }

  grantAdminPrivileges(targetIdentity: __Identity, adminLevel: string) {
    const __args = { targetIdentity, adminLevel };
    let __writer = new __BinaryWriter(1024);
    GrantAdminPrivileges.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("grant_admin_privileges", __argsBuffer, this.setCallReducerFlags.grantAdminPrivilegesFlags);
  }

  onGrantAdminPrivileges(callback: (ctx: ReducerEventContext, targetIdentity: __Identity, adminLevel: string) => void) {
    this.connection.onReducer("grant_admin_privileges", callback);
  }

  removeOnGrantAdminPrivileges(callback: (ctx: ReducerEventContext, targetIdentity: __Identity, adminLevel: string) => void) {
    this.connection.offReducer("grant_admin_privileges", callback);
  }

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  joinActiveGameSession(playerType: string) {
    const __args = { playerType };
    let __writer = new __BinaryWriter(1024);
    JoinActiveGameSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("join_active_game_session", __argsBuffer, this.setCallReducerFlags.joinActiveGameSessionFlags);
  }

  onJoinActiveGameSession(callback: (ctx: ReducerEventContext, playerType: string) => void) {
    this.connection.onReducer("join_active_game_session", callback);
  }

  removeOnJoinActiveGameSession(callback: (ctx: ReducerEventContext, playerType: string) => void) {
    this.connection.offReducer("join_active_game_session", callback);
  }

  listAdmins() {
    this.connection.callReducer("list_admins", new Uint8Array(0), this.setCallReducerFlags.listAdminsFlags);
  }

  onListAdmins(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("list_admins", callback);
  }

  removeOnListAdmins(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("list_admins", callback);
  }

  markClaimClaimed(sessionId: string, claimTransactionHash: string) {
    const __args = { sessionId, claimTransactionHash };
    let __writer = new __BinaryWriter(1024);
    MarkClaimClaimed.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("mark_claim_claimed", __argsBuffer, this.setCallReducerFlags.markClaimClaimedFlags);
  }

  onMarkClaimClaimed(callback: (ctx: ReducerEventContext, sessionId: string, claimTransactionHash: string) => void) {
    this.connection.onReducer("mark_claim_claimed", callback);
  }

  removeOnMarkClaimClaimed(callback: (ctx: ReducerEventContext, sessionId: string, claimTransactionHash: string) => void) {
    this.connection.offReducer("mark_claim_claimed", callback);
  }

  markEntryConsumed(sessionId: string) {
    const __args = { sessionId };
    let __writer = new __BinaryWriter(1024);
    MarkEntryConsumed.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("mark_entry_consumed", __argsBuffer, this.setCallReducerFlags.markEntryConsumedFlags);
  }

  onMarkEntryConsumed(callback: (ctx: ReducerEventContext, sessionId: string) => void) {
    this.connection.onReducer("mark_entry_consumed", callback);
  }

  removeOnMarkEntryConsumed(callback: (ctx: ReducerEventContext, sessionId: string) => void) {
    this.connection.offReducer("mark_entry_consumed", callback);
  }

  recordGuestGame(sessionId: string, guestId: string, score: number, questionsAnswered: number, correctAnswers: number, gameData: string) {
    const __args = { sessionId, guestId, score, questionsAnswered, correctAnswers, gameData };
    let __writer = new __BinaryWriter(1024);
    RecordGuestGame.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("record_guest_game", __argsBuffer, this.setCallReducerFlags.recordGuestGameFlags);
  }

  onRecordGuestGame(callback: (ctx: ReducerEventContext, sessionId: string, guestId: string, score: number, questionsAnswered: number, correctAnswers: number, gameData: string) => void) {
    this.connection.onReducer("record_guest_game", callback);
  }

  removeOnRecordGuestGame(callback: (ctx: ReducerEventContext, sessionId: string, guestId: string, score: number, questionsAnswered: number, correctAnswers: number, gameData: string) => void) {
    this.connection.offReducer("record_guest_game", callback);
  }

  recordPrizeDistribution(walletAddress: string, sessionId: string, prizeAmount: number, rank: number) {
    const __args = { walletAddress, sessionId, prizeAmount, rank };
    let __writer = new __BinaryWriter(1024);
    RecordPrizeDistribution.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("record_prize_distribution", __argsBuffer, this.setCallReducerFlags.recordPrizeDistributionFlags);
  }

  onRecordPrizeDistribution(callback: (ctx: ReducerEventContext, walletAddress: string, sessionId: string, prizeAmount: number, rank: number) => void) {
    this.connection.onReducer("record_prize_distribution", callback);
  }

  removeOnRecordPrizeDistribution(callback: (ctx: ReducerEventContext, walletAddress: string, sessionId: string, prizeAmount: number, rank: number) => void) {
    this.connection.offReducer("record_prize_distribution", callback);
  }

  recordQuestionAttempt(sessionId: string, audioFileName: string, selectedAnswer: number, correctAnswer: number, timeTaken: number, playerType: string) {
    const __args = { sessionId, audioFileName, selectedAnswer, correctAnswer, timeTaken, playerType };
    let __writer = new __BinaryWriter(1024);
    RecordQuestionAttempt.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("record_question_attempt", __argsBuffer, this.setCallReducerFlags.recordQuestionAttemptFlags);
  }

  onRecordQuestionAttempt(callback: (ctx: ReducerEventContext, sessionId: string, audioFileName: string, selectedAnswer: number, correctAnswer: number, timeTaken: number, playerType: string) => void) {
    this.connection.onReducer("record_question_attempt", callback);
  }

  removeOnRecordQuestionAttempt(callback: (ctx: ReducerEventContext, sessionId: string, audioFileName: string, selectedAnswer: number, correctAnswer: number, timeTaken: number, playerType: string) => void) {
    this.connection.offReducer("record_question_attempt", callback);
  }

  revokeAdminPrivileges(targetIdentity: __Identity) {
    const __args = { targetIdentity };
    let __writer = new __BinaryWriter(1024);
    RevokeAdminPrivileges.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("revoke_admin_privileges", __argsBuffer, this.setCallReducerFlags.revokeAdminPrivilegesFlags);
  }

  onRevokeAdminPrivileges(callback: (ctx: ReducerEventContext, targetIdentity: __Identity) => void) {
    this.connection.onReducer("revoke_admin_privileges", callback);
  }

  removeOnRevokeAdminPrivileges(callback: (ctx: ReducerEventContext, targetIdentity: __Identity) => void) {
    this.connection.offReducer("revoke_admin_privileges", callback);
  }

  startGameSession(sessionId: string, difficulty: string, gameMode: string, playerType: string) {
    const __args = { sessionId, difficulty, gameMode, playerType };
    let __writer = new __BinaryWriter(1024);
    StartGameSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("start_game_session", __argsBuffer, this.setCallReducerFlags.startGameSessionFlags);
  }

  onStartGameSession(callback: (ctx: ReducerEventContext, sessionId: string, difficulty: string, gameMode: string, playerType: string) => void) {
    this.connection.onReducer("start_game_session", callback);
  }

  removeOnStartGameSession(callback: (ctx: ReducerEventContext, sessionId: string, difficulty: string, gameMode: string, playerType: string) => void) {
    this.connection.offReducer("start_game_session", callback);
  }

  updateAnonymousSession(sessionId: string, gamesPlayed: number, totalScore: number, bestScore: number) {
    const __args = { sessionId, gamesPlayed, totalScore, bestScore };
    let __writer = new __BinaryWriter(1024);
    UpdateAnonymousSession.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_anonymous_session", __argsBuffer, this.setCallReducerFlags.updateAnonymousSessionFlags);
  }

  onUpdateAnonymousSession(callback: (ctx: ReducerEventContext, sessionId: string, gamesPlayed: number, totalScore: number, bestScore: number) => void) {
    this.connection.onReducer("update_anonymous_session", callback);
  }

  removeOnUpdateAnonymousSession(callback: (ctx: ReducerEventContext, sessionId: string, gamesPlayed: number, totalScore: number, bestScore: number) => void) {
    this.connection.offReducer("update_anonymous_session", callback);
  }

  updateGuestPlayer(guestId: string, gamesPlayed: number, totalScore: number, bestScore: number, achievements: string) {
    const __args = { guestId, gamesPlayed, totalScore, bestScore, achievements };
    let __writer = new __BinaryWriter(1024);
    UpdateGuestPlayer.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_guest_player", __argsBuffer, this.setCallReducerFlags.updateGuestPlayerFlags);
  }

  onUpdateGuestPlayer(callback: (ctx: ReducerEventContext, guestId: string, gamesPlayed: number, totalScore: number, bestScore: number, achievements: string) => void) {
    this.connection.onReducer("update_guest_player", callback);
  }

  removeOnUpdateGuestPlayer(callback: (ctx: ReducerEventContext, guestId: string, gamesPlayed: number, totalScore: number, bestScore: number, achievements: string) => void) {
    this.connection.offReducer("update_guest_player", callback);
  }

  updatePlayerStats(walletAddress: string, totalScore: number, gamesPlayed: number, bestScore: number, totalEarnings: number) {
    const __args = { walletAddress, totalScore, gamesPlayed, bestScore, totalEarnings };
    let __writer = new __BinaryWriter(1024);
    UpdatePlayerStats.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_player_stats", __argsBuffer, this.setCallReducerFlags.updatePlayerStatsFlags);
  }

  onUpdatePlayerStats(callback: (ctx: ReducerEventContext, walletAddress: string, totalScore: number, gamesPlayed: number, bestScore: number, totalEarnings: number) => void) {
    this.connection.onReducer("update_player_stats", callback);
  }

  removeOnUpdatePlayerStats(callback: (ctx: ReducerEventContext, walletAddress: string, totalScore: number, gamesPlayed: number, bestScore: number, totalEarnings: number) => void) {
    this.connection.offReducer("update_player_stats", callback);
  }

  updatePlayerType(newType: string) {
    const __args = { newType };
    let __writer = new __BinaryWriter(1024);
    UpdatePlayerType.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_player_type", __argsBuffer, this.setCallReducerFlags.updatePlayerTypeFlags);
  }

  onUpdatePlayerType(callback: (ctx: ReducerEventContext, newType: string) => void) {
    this.connection.onReducer("update_player_type", callback);
  }

  removeOnUpdatePlayerType(callback: (ctx: ReducerEventContext, newType: string) => void) {
    this.connection.offReducer("update_player_type", callback);
  }

  updatePrizePool(gameId: string, totalAmount: number, paidPlayers: number, freePlayers: number, winnerAddress: string | undefined, winnerScore: number | undefined, claimed: boolean) {
    const __args = { gameId, totalAmount, paidPlayers, freePlayers, winnerAddress, winnerScore, claimed };
    let __writer = new __BinaryWriter(1024);
    UpdatePrizePool.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_prize_pool", __argsBuffer, this.setCallReducerFlags.updatePrizePoolFlags);
  }

  onUpdatePrizePool(callback: (ctx: ReducerEventContext, gameId: string, totalAmount: number, paidPlayers: number, freePlayers: number, winnerAddress: string | undefined, winnerScore: number | undefined, claimed: boolean) => void) {
    this.connection.onReducer("update_prize_pool", callback);
  }

  removeOnUpdatePrizePool(callback: (ctx: ReducerEventContext, gameId: string, totalAmount: number, paidPlayers: number, freePlayers: number, winnerAddress: string | undefined, winnerScore: number | undefined, claimed: boolean) => void) {
    this.connection.offReducer("update_prize_pool", callback);
  }

  updateTrialStatus(walletAddress: string, trialGamesRemaining: number, trialCompleted: boolean) {
    const __args = { walletAddress, trialGamesRemaining, trialCompleted };
    let __writer = new __BinaryWriter(1024);
    UpdateTrialStatus.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_trial_status", __argsBuffer, this.setCallReducerFlags.updateTrialStatusFlags);
  }

  onUpdateTrialStatus(callback: (ctx: ReducerEventContext, walletAddress: string, trialGamesRemaining: number, trialCompleted: boolean) => void) {
    this.connection.onReducer("update_trial_status", callback);
  }

  removeOnUpdateTrialStatus(callback: (ctx: ReducerEventContext, walletAddress: string, trialGamesRemaining: number, trialCompleted: boolean) => void) {
    this.connection.offReducer("update_trial_status", callback);
  }

}

export class SetReducerFlags {
  addAudioFileFlags: __CallReducerFlags = 'FullUpdate';
  addAudioFile(flags: __CallReducerFlags) {
    this.addAudioFileFlags = flags;
  }

  createAnonymousSessionFlags: __CallReducerFlags = 'FullUpdate';
  createAnonymousSession(flags: __CallReducerFlags) {
    this.createAnonymousSessionFlags = flags;
  }

  createGameEntryFlags: __CallReducerFlags = 'FullUpdate';
  createGameEntry(flags: __CallReducerFlags) {
    this.createGameEntryFlags = flags;
  }

  createGuestPlayerFlags: __CallReducerFlags = 'FullUpdate';
  createGuestPlayer(flags: __CallReducerFlags) {
    this.createGuestPlayerFlags = flags;
  }

  createPendingClaimFlags: __CallReducerFlags = 'FullUpdate';
  createPendingClaim(flags: __CallReducerFlags) {
    this.createPendingClaimFlags = flags;
  }

  createPlayerFlags: __CallReducerFlags = 'FullUpdate';
  createPlayer(flags: __CallReducerFlags) {
    this.createPlayerFlags = flags;
  }

  createPrizePoolFlags: __CallReducerFlags = 'FullUpdate';
  createPrizePool(flags: __CallReducerFlags) {
    this.createPrizePoolFlags = flags;
  }

  endGameSessionFlags: __CallReducerFlags = 'FullUpdate';
  endGameSession(flags: __CallReducerFlags) {
    this.endGameSessionFlags = flags;
  }

  getActiveGameSessionFlags: __CallReducerFlags = 'FullUpdate';
  getActiveGameSession(flags: __CallReducerFlags) {
    this.getActiveGameSessionFlags = flags;
  }

  getAllGameEntriesAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllGameEntriesAdmin(flags: __CallReducerFlags) {
    this.getAllGameEntriesAdminFlags = flags;
  }

  getAllGameSessionsAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllGameSessionsAdmin(flags: __CallReducerFlags) {
    this.getAllGameSessionsAdminFlags = flags;
  }

  getAllGuestGameSessionsAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllGuestGameSessionsAdmin(flags: __CallReducerFlags) {
    this.getAllGuestGameSessionsAdminFlags = flags;
  }

  getAllGuestPlayersAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllGuestPlayersAdmin(flags: __CallReducerFlags) {
    this.getAllGuestPlayersAdminFlags = flags;
  }

  getAllPendingClaimsAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllPendingClaimsAdmin(flags: __CallReducerFlags) {
    this.getAllPendingClaimsAdminFlags = flags;
  }

  getAllPlayerStatsAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllPlayerStatsAdmin(flags: __CallReducerFlags) {
    this.getAllPlayerStatsAdminFlags = flags;
  }

  getAllPlayersAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllPlayersAdmin(flags: __CallReducerFlags) {
    this.getAllPlayersAdminFlags = flags;
  }

  getAllQuestionAttemptsAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllQuestionAttemptsAdmin(flags: __CallReducerFlags) {
    this.getAllQuestionAttemptsAdminFlags = flags;
  }

  getLeaderboardFlags: __CallReducerFlags = 'FullUpdate';
  getLeaderboard(flags: __CallReducerFlags) {
    this.getLeaderboardFlags = flags;
  }

  getLeaderboardAdminFlags: __CallReducerFlags = 'FullUpdate';
  getLeaderboardAdmin(flags: __CallReducerFlags) {
    this.getLeaderboardAdminFlags = flags;
  }

  getPlayerStatsFlags: __CallReducerFlags = 'FullUpdate';
  getPlayerStats(flags: __CallReducerFlags) {
    this.getPlayerStatsFlags = flags;
  }

  getRandomAudioFilesFlags: __CallReducerFlags = 'FullUpdate';
  getRandomAudioFiles(flags: __CallReducerFlags) {
    this.getRandomAudioFilesFlags = flags;
  }

  getTopEarnersFlags: __CallReducerFlags = 'FullUpdate';
  getTopEarners(flags: __CallReducerFlags) {
    this.getTopEarnersFlags = flags;
  }

  getTrialLeaderboardFlags: __CallReducerFlags = 'FullUpdate';
  getTrialLeaderboard(flags: __CallReducerFlags) {
    this.getTrialLeaderboardFlags = flags;
  }

  getTrialLeaderboardAdminFlags: __CallReducerFlags = 'FullUpdate';
  getTrialLeaderboardAdmin(flags: __CallReducerFlags) {
    this.getTrialLeaderboardAdminFlags = flags;
  }

  grantAdminPrivilegesFlags: __CallReducerFlags = 'FullUpdate';
  grantAdminPrivileges(flags: __CallReducerFlags) {
    this.grantAdminPrivilegesFlags = flags;
  }

  joinActiveGameSessionFlags: __CallReducerFlags = 'FullUpdate';
  joinActiveGameSession(flags: __CallReducerFlags) {
    this.joinActiveGameSessionFlags = flags;
  }

  listAdminsFlags: __CallReducerFlags = 'FullUpdate';
  listAdmins(flags: __CallReducerFlags) {
    this.listAdminsFlags = flags;
  }

  markClaimClaimedFlags: __CallReducerFlags = 'FullUpdate';
  markClaimClaimed(flags: __CallReducerFlags) {
    this.markClaimClaimedFlags = flags;
  }

  markEntryConsumedFlags: __CallReducerFlags = 'FullUpdate';
  markEntryConsumed(flags: __CallReducerFlags) {
    this.markEntryConsumedFlags = flags;
  }

  recordGuestGameFlags: __CallReducerFlags = 'FullUpdate';
  recordGuestGame(flags: __CallReducerFlags) {
    this.recordGuestGameFlags = flags;
  }

  recordPrizeDistributionFlags: __CallReducerFlags = 'FullUpdate';
  recordPrizeDistribution(flags: __CallReducerFlags) {
    this.recordPrizeDistributionFlags = flags;
  }

  recordQuestionAttemptFlags: __CallReducerFlags = 'FullUpdate';
  recordQuestionAttempt(flags: __CallReducerFlags) {
    this.recordQuestionAttemptFlags = flags;
  }

  revokeAdminPrivilegesFlags: __CallReducerFlags = 'FullUpdate';
  revokeAdminPrivileges(flags: __CallReducerFlags) {
    this.revokeAdminPrivilegesFlags = flags;
  }

  startGameSessionFlags: __CallReducerFlags = 'FullUpdate';
  startGameSession(flags: __CallReducerFlags) {
    this.startGameSessionFlags = flags;
  }

  updateAnonymousSessionFlags: __CallReducerFlags = 'FullUpdate';
  updateAnonymousSession(flags: __CallReducerFlags) {
    this.updateAnonymousSessionFlags = flags;
  }

  updateGuestPlayerFlags: __CallReducerFlags = 'FullUpdate';
  updateGuestPlayer(flags: __CallReducerFlags) {
    this.updateGuestPlayerFlags = flags;
  }

  updatePlayerStatsFlags: __CallReducerFlags = 'FullUpdate';
  updatePlayerStats(flags: __CallReducerFlags) {
    this.updatePlayerStatsFlags = flags;
  }

  updatePlayerTypeFlags: __CallReducerFlags = 'FullUpdate';
  updatePlayerType(flags: __CallReducerFlags) {
    this.updatePlayerTypeFlags = flags;
  }

  updatePrizePoolFlags: __CallReducerFlags = 'FullUpdate';
  updatePrizePool(flags: __CallReducerFlags) {
    this.updatePrizePoolFlags = flags;
  }

  updateTrialStatusFlags: __CallReducerFlags = 'FullUpdate';
  updateTrialStatus(flags: __CallReducerFlags) {
    this.updateTrialStatusFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get activeGameSessions(): ActiveGameSessionsTableHandle {
    // clientCache is a private property
    return new ActiveGameSessionsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ActiveGameSession>(REMOTE_MODULE.tables.active_game_sessions));
  }

  get admins(): AdminsTableHandle {
    // clientCache is a private property
    return new AdminsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Admin>(REMOTE_MODULE.tables.admins));
  }

  get anonymousSessions(): AnonymousSessionsTableHandle {
    // clientCache is a private property
    return new AnonymousSessionsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<AnonymousSession>(REMOTE_MODULE.tables.anonymous_sessions));
  }

  get audioFiles(): AudioFilesTableHandle {
    // clientCache is a private property
    return new AudioFilesTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<AudioFile>(REMOTE_MODULE.tables.audio_files));
  }

  get gameEntries(): GameEntriesTableHandle {
    // clientCache is a private property
    return new GameEntriesTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<GameEntry>(REMOTE_MODULE.tables.game_entries));
  }

  get gameSessions(): GameSessionsTableHandle {
    // clientCache is a private property
    return new GameSessionsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<GameSession>(REMOTE_MODULE.tables.game_sessions));
  }

  get guestGameSessions(): GuestGameSessionsTableHandle {
    // clientCache is a private property
    return new GuestGameSessionsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<GuestGameSession>(REMOTE_MODULE.tables.guest_game_sessions));
  }

  get guestPlayers(): GuestPlayersTableHandle {
    // clientCache is a private property
    return new GuestPlayersTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<GuestPlayer>(REMOTE_MODULE.tables.guest_players));
  }

  get pendingClaims(): PendingClaimsTableHandle {
    // clientCache is a private property
    return new PendingClaimsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PendingClaim>(REMOTE_MODULE.tables.pending_claims));
  }

  get playerStats(): PlayerStatsTableHandle {
    // clientCache is a private property
    return new PlayerStatsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PlayerStats>(REMOTE_MODULE.tables.player_stats));
  }

  get players(): PlayersTableHandle {
    // clientCache is a private property
    return new PlayersTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Player>(REMOTE_MODULE.tables.players));
  }

  get prizeHistory(): PrizeHistoryTableHandle {
    // clientCache is a private property
    return new PrizeHistoryTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PrizeHistory>(REMOTE_MODULE.tables.prize_history));
  }

  get prizePools(): PrizePoolsTableHandle {
    // clientCache is a private property
    return new PrizePoolsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PrizePool>(REMOTE_MODULE.tables.prize_pools));
  }

  get questionAttempts(): QuestionAttemptsTableHandle {
    // clientCache is a private property
    return new QuestionAttemptsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<QuestionAttempt>(REMOTE_MODULE.tables.question_attempts));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
