// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type PlayerStats = {
  playerIdentity: __Identity,
  playerType: string,
  totalGames: number,
  totalScore: number,
  bestScore: number,
  averageScore: number,
  totalQuestionsAnswered: number,
  totalCorrectAnswers: number,
  lastPlayed: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const PlayerStats = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "playerIdentity", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "playerType", algebraicType: __AlgebraicTypeValue.String},
        { name: "totalGames", algebraicType: __AlgebraicTypeValue.U32},
        { name: "totalScore", algebraicType: __AlgebraicTypeValue.U32},
        { name: "bestScore", algebraicType: __AlgebraicTypeValue.U32},
        { name: "averageScore", algebraicType: __AlgebraicTypeValue.F64},
        { name: "totalQuestionsAnswered", algebraicType: __AlgebraicTypeValue.U32},
        { name: "totalCorrectAnswers", algebraicType: __AlgebraicTypeValue.U32},
        { name: "lastPlayed", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PlayerStats): void {
    __AlgebraicTypeValue.serializeValue(writer, PlayerStats.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerStats {
    return __AlgebraicTypeValue.deserializeValue(reader, PlayerStats.getTypeScriptAlgebraicType());
  },

}

export default PlayerStats;


