// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type PrizeHistory = {
  walletAddress: string,
  sessionId: string,
  prizeAmount: number,
  rank: number,
  gameTimestamp: __Timestamp,
  claimed: boolean,
};
/**
 * An object for generated helper functions.
 */
export const PrizeHistory = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "walletAddress", algebraicType: __AlgebraicTypeValue.String},
        { name: "sessionId", algebraicType: __AlgebraicTypeValue.String},
        { name: "prizeAmount", algebraicType: __AlgebraicTypeValue.F64},
        { name: "rank", algebraicType: __AlgebraicTypeValue.U32},
        { name: "gameTimestamp", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "claimed", algebraicType: __AlgebraicTypeValue.Bool},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PrizeHistory): void {
    __AlgebraicTypeValue.serializeValue(writer, PrizeHistory.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PrizeHistory {
    return __AlgebraicTypeValue.deserializeValue(reader, PrizeHistory.getTypeScriptAlgebraicType());
  },

}

export default PrizeHistory;


