// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type QuestionAttempt = {
  sessionId: string,
  playerIdentity: __Identity,
  playerType: string,
  audioFileId: string,
  selectedAnswer: number,
  correctAnswer: number,
  isCorrect: boolean,
  timeTaken: number,
  answeredAt: __Timestamp,
};
/**
 * An object for generated helper functions.
 */
export const QuestionAttempt = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "sessionId", algebraicType: __AlgebraicTypeValue.String},
        { name: "playerIdentity", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "playerType", algebraicType: __AlgebraicTypeValue.String},
        { name: "audioFileId", algebraicType: __AlgebraicTypeValue.String},
        { name: "selectedAnswer", algebraicType: __AlgebraicTypeValue.U32},
        { name: "correctAnswer", algebraicType: __AlgebraicTypeValue.U32},
        { name: "isCorrect", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "timeTaken", algebraicType: __AlgebraicTypeValue.F64},
        { name: "answeredAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: QuestionAttempt): void {
    __AlgebraicTypeValue.serializeValue(writer, QuestionAttempt.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): QuestionAttempt {
    return __AlgebraicTypeValue.deserializeValue(reader, QuestionAttempt.getTypeScriptAlgebraicType());
  },

}

export default QuestionAttempt;


